name: variant-pipeline
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.11
  - bwa
  - samtools
  - bcftools
  - fastp
  - htslib
  - tabix
  - pip
  - pip:
      - pandas
      - jinja2
